### ISSUE TITLE
Help make openapi 3.1 spec a default in java community!

### ISSUE THREAD

**Issue by bgalek** [erosb/kappa#9]
Hi, nice library!
I think you may be interested in this spring doc pool - shift the community to openapi 3.1 spec by default ;)

https://github.com/springdoc/springdoc-openapi/discussions/2790

**Comment by erosb** [comment]
Voted :)
FYI [OpenAPI 4 "Moonwalk"](https://github.com/OAI/sig-moonwalk) is coming next year, probably :)

**Comment by bgalek** [comment]
thx :)
